version: "2"

linters:
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
            - '!$test'
          allow:
            - $gostd
            - k8s.io
            - sigs.k8s.io
            - github.com
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - test/utils/azure/azure_helpers.go
      - vendor$
formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - vendor$
