---
kind: Service
apiVersion: v1
metadata:
  name: smb-server
  namespace: default
  labels:
    app: smb-server
spec:
  type: LoadBalancer
  selector:
    app: smb-server
  ports:
    - port: 445
      name: smb-server
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: smb-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smb-server
  template:
    metadata:
      name: smb-server
      labels:
        app: smb-server
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: smb-server
          image: dockurr/samba
          env:
            - name: NAME
              value: share
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: smbcreds
                  key: username
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: smbcreds
                  key: password
          volumeMounts:
            - mountPath: /storage
              name: data-volume
          ports:
            - containerPort: 445
      volumes:
        - name: data-volume
          hostPath:
            path: /home/kubernetes/smbshare-volume  # modify this to specify another path to store smb share data
            type: DirectoryOrCreate
