image:
  baseRepo: registry.k8s.io/sig-storage
  smb:
    repository: registry.k8s.io/sig-storage/smbplugin
    tag: v1.19.1
    pullPolicy: IfNotPresent
  csiProvisioner:
    repository: /csi-provisioner
    tag: v5.3.0
    pullPolicy: IfNotPresent
  csiResizer:
    repository: registry.k8s.io/sig-storage/csi-resizer
    tag: v1.14.0
    pullPolicy: IfNotPresent
  livenessProbe:
    repository: /livenessprobe
    tag: v2.17.0
    pullPolicy: IfNotPresent
  nodeDriverRegistrar:
    repository: /csi-node-driver-registrar
    tag: v2.15.0
    pullPolicy: IfNotPresent
  csiproxy:
    repository: ghcr.io/kubernetes-sigs/sig-windows/csi-proxy
    tag: v1.1.2
    pullPolicy: IfNotPresent

serviceAccount:
  create: true # When true, service accounts will be created for you. Set to false if you want to use your own.
  controller: csi-smb-controller-sa
  node: csi-smb-node-sa

rbac:
  create: true
  name: smb

driver:
  name: smb.csi.k8s.io

feature:
  enableGetVolumeStats: true
  enableInlineVolume: true

controller:
  name: csi-smb-controller
  replicas: 1
  dnsPolicy: ClusterFirstWithHostNet  # available values: Default, ClusterFirstWithHostNet, ClusterFirst
  metricsPort: 29644
  livenessProbe:
    healthPort: 29642
  runOnMaster: false
  runOnControlPlane: false
  logLevel: 5
  workingMountDir: "/tmp"
  resources:
    csiProvisioner:
      limits:
        memory: 400Mi
      requests:
        cpu: 10m
        memory: 20Mi
    csiResizer:
      limits:
        memory: 400Mi
      requests:
        cpu: 10m
        memory: 20Mi
    livenessProbe:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
    smb:
      limits:
        memory: 200Mi
      requests:
        cpu: 10m
        memory: 20Mi
  affinity: {}
  nodeSelector: {}
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/controlplane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "CriticalAddonsOnly"
      operator: "Exists"
      effect: "NoSchedule"

node:
  maxUnavailable: 1
  logLevel: 5
  livenessProbe:
    healthPort: 29643
  affinity: {}
  nodeSelector: {}

linux:
  enabled: true
  dsName: csi-smb-node # daemonset name
  dnsPolicy: ClusterFirstWithHostNet  # available values: Default, ClusterFirstWithHostNet, ClusterFirst
  kubelet: /var/lib/kubelet
  krb5CacheDirectory: "" # directory for kerberos credential cache, empty string means default(/var/lib/kubelet/kerberos/)
  krb5Prefix: "" # prefix for kerberos credential cache, empty string means default(krb5cc_)
  tolerations:
    - operator: "Exists"
  resources:
    livenessProbe:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
    nodeDriverRegistrar:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
    smb:
      limits:
        memory: 200Mi
      requests:
        cpu: 10m
        memory: 20Mi

windows:
  enabled: true
  useHostProcessContainers: true
  dsName: csi-smb-node-win # daemonset name
  kubelet: 'C:\var\lib\kubelet'
  removeSMBMappingDuringUnmount: true
  tolerations:
    - key: "node.kubernetes.io/os"
      operator: "Exists"
      effect: "NoSchedule"
  resources:
    livenessProbe:
      limits:
        memory: 150Mi
      requests:
        cpu: 10m
        memory: 40Mi
    nodeDriverRegistrar:
      limits:
        memory: 150Mi
      requests:
        cpu: 10m
        memory: 40Mi
    smb:
      limits:
        memory: 600Mi
      requests:
        cpu: 10m
        memory: 40Mi
  csiproxy:
    enabled: false # required if windows.enabled is true and useHostProcessContainers is false, but may be installed manually also
    dsName: csi-proxy-win # daemonset name
    tolerations: {}
    affinity: {}
    username: "NT AUTHORITY\\SYSTEM"
    nodeSelector:
      "kubernetes.io/os": windows

customLabels: {}
## Collection of annotations to add to all the pods
podAnnotations: {}
## Collection of labels to add to all the pods
podLabels: {}
## Leverage a PriorityClass to ensure your pods survive resource shortages
## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
priorityClassName: system-cluster-critical
## Security context give the opportunity to run container as nonroot by setting a securityContext
## by example :
## securityContext: { runAsUser: 1001 }
securityContext: { seccompProfile: {type: RuntimeDefault} }
## StorageClass resources for creating multiple storage classes:
# storageClasses:
#   - name: smb-csi
#     annotations:
#       storageclass.kubernetes.io/is-default-class: "true"
#     parameters:
#       source: "//smb-server.default.svc.cluster.local/share"
#       # if csi.storage.k8s.io/provisioner-secret is provided, will create a sub directory
#       # with PV name under source
#       csi.storage.k8s.io/provisioner-secret-name: smbcreds
#       csi.storage.k8s.io/provisioner-secret-namespace: default
#       csi.storage.k8s.io/node-stage-secret-name: smbcreds
#       csi.storage.k8s.io/node-stage-secret-namespace: default
#     reclaimPolicy: Delete
#     volumeBindingMode: Immediate
#     allowVolumeExpansion: true
#     mountOptions:
#       - dir_mode=0777
#       - file_mode=0777
#       - noperm
#       - mfsymlinks
#       - cache=strict
#       - noserverino  # required to prevent data corruption
#   - name: smb-csi-retain
#     parameters:
#       source: "//smb-server.default.svc.cluster.local/share"
#       # if csi.storage.k8s.io/provisioner-secret is provided, will create a sub directory
#       # with PV name under source
#       csi.storage.k8s.io/provisioner-secret-name: smbcreds
#       csi.storage.k8s.io/provisioner-secret-namespace: default
#       csi.storage.k8s.io/node-stage-secret-name: smbcreds
#       csi.storage.k8s.io/node-stage-secret-namespace: default
#     reclaimPolicy: Delete
#     volumeBindingMode: Immediate
#     allowVolumeExpansion: true
#     mountOptions:
#       - dir_mode=0777
#       - file_mode=0777
#       - noperm
#       - mfsymlinks
#       - cache=strict
#       - noserverino  # required to prevent data corruption
