name: Linux Unit tests
on:
    pull_request: {}
    push: {}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v6
      with:
        go-version: ^1.25
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Install packages
      run: |
        sudo apt update
        sudo apt install cifs-utils procps -y

    - name: Build Test
      run: |
        export PATH=$PATH:$HOME/.local/bin
        go test -race -covermode=atomic -coverprofile=profile.cov ./pkg/...
        export DOCKER_CLI_EXPERIMENTAL=enabled && make container

    - name: Sanity test
      env:
        GITHUB_ACTIONS: true
      run: |
        export PATH=$PATH:$HOME/.local/bin
        make
        echo "is running in github actions: $GITHUB_ACTIONS"
        make sanity-test

    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=profile.cov -service=github
